name: CrateKeyShop
author: MasApip
main: CrateKeyShop\Main
version: 1.0.0
api: [3.0.0, 4.0.0]
depend: ["FormAPI", "EconomyAPI", "MysteryCrate"]
commands:
    keyshop:
        default: true
        description: CrateKey Shop 
