---
#Common Settings
common.price: 50000
common.amount: 1 
common.success.purchase: "§aYou have successfully purchased a Common key!"
#UnCommon Settings
uncommon.price: 100000
uncommon.amount: 1 
uncommon.success.purchase: "§aYou have successfully purchased a UnCommon key!"
#Mythic Settings
mythic.price: 150000
mythic.amount: 1 
mythic.success.purchase: "§aYou have successfully purchased a Mythic key!"
#Legendary Settings
legendary.price: 200000
legendary.amount: 1 
legendary.success.purchase: "§aYou have successfully purchased a Legendary key!"
#More Message
not.enough.money: "§cYou don't have enough money!"
quit.message: "§aThanks for visiting shop!"
form.content: "§eHello, {PLAYER}. Your Money: §a{MONEY}, make sure you have enough money:)"
...
